### ISSUE TITLE
/Users/me/Downloads/mwa2_demo/mwa2/munkiwebadmin/settings.py

### ISSUE THREAD

**Issue by blackberryhell** [munki/mwa2#25]
I might be missing something but when I attempt to go to /Users/mcclemja/Downloads/mwa2_demo/mwa2/munkiwebadmin/settings.py to edit it I cannot find the file or the directory.

 cd /Users/me/Downloads/mwa2_demo/mwa2/munkiwebadmin/
bash: cd: /Users/me/Downloads/mwa2_demo/mwa2/munkiwebadmin/: No such file or directory

**Comment by gregneagle** [comment]
So what additional investigation/looking around have you done?

```
ls /Users/me/Downloads/
ls /Users/me/Downloads/mwa2_demo
ls /Users/me/Downloads/mwa2_demo/mwa2
```

We don't really know what you are working with here.

**Comment by blackberryhell** [comment]
H Greg

Sorry for the delay, Friday and Saturday are my weekend here in sunny Saudi
Arabia. When I run the initial config script I am getting the following

bash-3.2# bash /Users/user/Downloads/mwa2_demo/run_mwa2.sh

**\* Cloning MWA2 from GitHub ***

xcode-select: note: no developer tools were found at
'/Applications/Xcode.app', requesting install. Choose an option in the
dialog to download the command line developer tools.

**\* Copying settings template ***

cp: ./mwa2/munkiwebadmin/settings_template.py: No such file or directory

Edit /Users/users/Downloads/mwa2_demo/mwa2/munkiwebadmin/settings.py:

```
Change MUNKI_REPO_DIR (near the end of the file) to point to your Munki
```

repo.

Then run this script again to continue setup tasks.

I cannot find the file
/Users/users/Downloads/mwa2_demo/mwa2/munkiwebadmin/settings.py,
do I create it myself?

Regards

Alex

**Comment by gregneagle** [comment]
I imagine that more than `/Users/users/Downloads/mwa2_demo/mwa2/munkiwebadmin/settings.py` is missing; I'm betting the entire `/Users/users/Downloads/mwa2_demo/mwa2` directory is missing.

I did ask you to show me the contents of the mwa2_demo folder. You didn't, so I'm just having to guess here.

I'm guessing your problem is here:

```
*** Cloning MWA2 from GitHub ***

xcode-select: note: no developer tools were found at
'/Applications/Xcode.app', requesting install. Choose an option in the
dialog to download the command line developer tools.
```

At this point, the script is attempting to use the `git` command to clone the mwa2 project locally to your machine. you are getting a warning:

```
xcode-select: note: no developer tools were found at
'/Applications/Xcode.app', requesting install. Choose an option in the
dialog to download the command line developer tools.
```

This means that neither Xcode, the command-line developer tools, or a standalone install of `git` are present and the OS is offering to install the developer tools for you.

You'll need a functioning install of `git` to successfully use the script.

Type `git --version` at a command prompt and allow the OS to install the command-line developer tools, or install Xcode from the App Store, or install git from https://git-scm.com/ and run the script again.

If this isn't the case, then please show me the contents of the directories as I asked before:

```
ls /Users/me/Downloads/mwa2_demo
ls /Users/me/Downloads/mwa2_demo/mwa2
``
```

**Comment by blackberryhell** [comment]
Cheers Greg, I was fairly certain I had xcode but I will check it out.

**Comment by gregneagle** [comment]
Closing this old support issue
